[tool.bumpversion]
current_version = "0.1.0"
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "uv.lock"
search = 'name = "project-name"\nversion = "{current_version}"'
replace = 'name = "project-name"\nversion = "{new_version}"'
regex = true
